services:
  db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paygridtcc
      POSTGRES_DB: paygrid
    ports:
      - "5432:5432"
